### ISSUE TITLE
z2M ne démarre pas avec ma pizigate

### ISSUE THREAD

**Issue by toto6976** [fairecasoimeme/ZiGate#413]
J'ai HA Supervised sur raspberry pi 3 et une pizigate v1
```
Voici le log de Z2M : 
17:41:09] INFO: Preparing to start...
[17:41:11] INFO: Socat not enabled
[17:41:16] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-10-12 17:41:31] info: 	z2m: Logging to console, file (filename: log.log)
[2024-10-12 17:41:31] info: 	z2m: Starting Zigbee2MQTT version 1.40.2 (commit #unknown)
[2024-10-12 17:41:31] info: 	z2m: Starting zigbee-herdsman (2.1.3)
[2024-10-12 17:41:33] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-12 17:41:33] error: 	z2m: Failed to start zigbee
[2024-10-12 17:41:33] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-12 17:41:33] error: 	z2m: Exiting...
[2024-10-12 17:41:33] error: 	z2m: Error: failed to connect to zigate adapter Error: I/O error setting custom baud rate of 115200
    at ZiGateAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/zigate/adapter/zigateAdapter.ts:95:19)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
```

**Comment by vchgn** [comment]
Bonjour,

Dans le fichier de configuration avez-vous ajouté l'option "adapter: zigate" ?
